name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Set auto-version
        run: echo "GORELEASER_CURRENT_TAG=v0.0.$(git rev-list --count HEAD)" >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --skip-validate
          workdir: cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
